### PR TITLE
Prevent infinite redirects when at root path

### PR DESCRIPTION
**Pull request by nicksrandall**
I'm getting infinite redirects when I request the static files' root path. This fixes the problem.

### CODE REVIEW

**Comment by dmitshur** [comment]
Hi @nicksrandall, thanks for the PR.

Can you please provide information for how to reproduce this? I'd like to understand the issue better.

The code you've edited is based on code from [`"net/http".FileServer`](https://godoc.org/net/http#FileServer), see https://github.com/golang/go/blob/361af94d5d4df310a90d924b4ce3dd4e3c96ee38/src/net/http/fs.go#L565-L578. The code there doesn't seem to include this change. In fact, it looks like it might even panic if `url` were `""`.

If this is a real problem, I want to also check whether `"net/http".FileServer` would need to be fixed too.

Mind filing an issue about this? That way we can leave this PR for the discussion of the fix.

**Comment by nicksrandall** [comment]
Sure, I'll create a small repo that reproduces the problem for you to test.

**Comment by nicksrandall** [comment]
@shurcooL here is a repo that reproduces the problem. https://github.com/nicksrandall/httpgzip-test. I have verified that this issue does NOT happen when I use `http.FileServer` but I have not yet figured out why or where the difference is.

This is making me realize that my fix should probably be somewhere else in the code.

**Comment by dmitshur** [comment]
Thanks, I will try it soon.

> This is making me realize that my fix should probably be somewhere else in the code.

Just by looking at the code, I can see that a fix would be:

```diff
 // this will give infinate redirects
-http.Handle("/static/", http.StripPrefix("/static/", httpgzip.FileServer(http.Dir("static"), httpgzip.FileServerOptions{})))
+http.Handle("/static/", http.StripPrefix("/static", httpgzip.FileServer(http.Dir("static"), httpgzip.FileServerOptions{})))
```

You don't want to be stripping off the second slash. See [here](https://github.com/shurcooL/home/blob/9c57e59a05baa9513b847fd945865935b7e529c2/main.go#L90) for an example of `StripPrefix` usage.

But I think this is likely something I'll want to fix in `httpgzip` anyway. So thanks for reporting.

**Comment by dmitshur** [comment]
Ok, I've investigated this.

The reason it's not a problem with `"net/http".FileServer` is because it does this:

```Go
func (f *fileHandler) ServeHTTP(w ResponseWriter, r *Request) {
	upath := r.URL.Path
	if !strings.HasPrefix(upath, "/") {
		upath = "/" + upath
		r.URL.Path = upath
	}
	serveFile(w, r, f.root, path.Clean(upath), true)
}
```

See https://github.com/golang/go/commit/3745716bc3940f471137bf06fbe8c042257a43d3 where it was fixed upstream.

I think your fix is reasonable, so I'll merge this. I'll just add a test case for this. Thanks!

**Review by dmitshur — APPROVED** [review]
LGTM. Thanks again!

**Pull request merged**
